version: "3"
services:

  db:
    image: "postgres"
    container_name: "my_postgres"
    environment:
      - POSTGRES_USER=john
      - POSTGRES_PASSWORD=pwd0123456789
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
      - "54320:5432"
    volumes:
      - ./dbdata:/var/lib/postgresql/data

  scraper:
    build:
      dockerfile: scraper.Dockerfile
      context: .
    container_name: "scraper-container"
#    volumes:
#      - .:/var/lib/app

volumes:
  dbdata: